"""create processes table

Revision ID: 78a78e64915e
Revises: 7da2f4fffe78
Create Date: 2026-08-03 21:42:47.935113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a78e64915e'
down_revision: Union[str, Sequence[str], None] = '7da2f4fffe78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('executable', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_process_asset', 'processes', ['asset_id'], unique=False)
    op.create_index('idx_process_name', 'processes', ['name'], unique=False)
    op.create_index('idx_process_pid', 'processes', ['pid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_process_pid', table_name='processes')
    op.drop_index('idx_process_name', table_name='processes')
    op.drop_index('idx_process_asset', table_name='processes')
    op.drop_table('processes')
    # ### end Alembic commands ###
