"""link metrics to assets

Revision ID: 892123732022
Revises: f8f3d68843f4
Create Date: 2026-07-29 19:48:01.335797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892123732022'
down_revision: Union[str, Sequence[str], None] = 'f8f3d68843f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'metrics', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_column('metrics', 'asset_id')
    # ### end Alembic commands ###
