"""add resolved_at to alerts

Revision ID: 9ea44631c22e
Revises: 78a78e64915e
Create Date: 2026-08-05 07:11:15.632846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea44631c22e'
down_revision: Union[str, Sequence[str], None] = '78a78e64915e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'resolved_at')
    # ### end Alembic commands ###
