"""add network monitoring

Revision ID: dfe223835bf8
Revises: 206692ab8cb8
Create Date: 2026-07-31 22:39:10.110977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe223835bf8'
down_revision: Union[str, Sequence[str], None] = '206692ab8cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_interfaces',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('interface_name', sa.String(length=100), nullable=False),
    sa.Column('interface_type', sa.String(length=50), nullable=False),
    sa.Column('ipv4_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('link_speed', sa.Integer(), nullable=False),
    sa.Column('mtu', sa.Integer(), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_metrics',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=False),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('bytes_received', sa.BigInteger(), nullable=False),
    sa.Column('packets_sent', sa.BigInteger(), nullable=False),
    sa.Column('packets_received', sa.BigInteger(), nullable=False),
    sa.Column('upload_speed', sa.Float(), nullable=False),
    sa.Column('download_speed', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['interface_id'], ['network_interfaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_network_metric_asset', 'network_metrics', ['asset_id'], unique=False)
    op.create_index('idx_network_metric_created', 'network_metrics', ['created_at'], unique=False)
    op.create_index('idx_network_metric_interface', 'network_metrics', ['interface_id'], unique=False)
    op.alter_column('metrics', 'asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_network_metric_interface', table_name='network_metrics')
    op.drop_index('idx_network_metric_created', table_name='network_metrics')
    op.drop_index('idx_network_metric_asset', table_name='network_metrics')
    op.drop_table('network_metrics')
    op.drop_table('network_interfaces')
    # ### end Alembic commands ###
